-- https://projecteuler.net/problem=2
--
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

main :: IO ()
main = print . sum $ filter even $ fibs `lessThan` 4000000
  where lessThan xs n = takeWhile (< n) xs
        fibs = fib 0 1
          where fib :: Integer -> Integer -> [Integer]
                fib x y = x : fib y (x + y)
