/*
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main()
{
    unsigned long sum = 0, prev = 0, cur = 1, next;

    /* until the current Fibonacci number is greater than 4,000,000 */
    while (cur <= 4000000)
    {
        /* add Fibonacci numbers divisible by 2 to the sum */
        if (cur % 2 == 0)
        {
            sum += cur;
        }

        /* move on to the next Fibonacci number */
        next = prev + cur;
        prev = cur;
        cur = next;
    }

    /* print the result */
    printf("%ld\n", sum);

    /* process completes successfully */
    return 0;
}
